# Generated by Django 2.2.3 on 2019-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('person_number_one', models.CharField(blank=True, default='', max_length=100)),
                ('person_number_two', models.CharField(blank=True, default='', max_length=100)),
                ('property_name_municipality', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
